### ISSUE TITLE
Dinge die noch erledigt werden müssen

### ISSUE THREAD

**Issue by Fingadumbledore** [hyperbel/MatheProjekt22_23#19]
- [x] Kurvendiskusion ( Extremwerte Wendepunkte Sattelpunkte Ableitungen Nullstellen) #14 
- [x] Ableitungen müssen angezeigt werden
- [x] Trigo und integral fixen @Fingadumbledore 
- [x] Alles in das erste Fenster einbauen und dann per button wechseln
- [x] Zoom Funktion (Trigo,expo,integral = FERTIG) #12 
- [x] Verlauf (zeigt sachen an)
- [x] Erklärungen für die verschiedenen sachen #17 
- [x] login fixen
- [x] gantt
- [x] Graph löschen (Trigo,expo,integral = FERTIG)
- [x] Kleine Dokumentation
- [x] #20 
- [x] #21 
- [x] #22 
- [x] Datenbank fixen
- [x] terme eingeben von Verlauf fixen
- [x] vlt. Icon einbauen
- [ ] bilder bei der Hilfe

# Sachen die gemacht werden können wenn genug Zeit
- [ ] willkommen witźzard
- [ ] Verlauf kann gelöscht werden
- [ ] #6 
- [ ] #8 
- [ ] Kommazahlen werden im Terme-Eingeben Frame als ganze gewertet (z.b.: 0.5 -> 5)
